compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU # Use DDP
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16 # Match your bnb compute dtype
num_machines: 1
num_processes: 8 # Your number of GPUs
same_network: true
use_cpu: false
# main_process_port: 0
# main_process_ip: 0
