import argparse
import json
import pandas as pd
import torch
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
import re
import xml.etree.ElementTree as ET
from peft import PeftModel
from accelerate import Accelerator
import random

from src.data import DiffExpressionDataset

def load_model_and_tokenizer(model_path, args, device, accelerator):
    """Loads a Hugging Face model and tokenizer to a specific device."""
    if accelerator.is_main_process:
        print(f"Loading model from: {model_path}")
        
    if args.lora_checkpoint:
        model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16, trust_remote_code=True, attn_implementation="flash_attention_2" if torch.cuda.is_bf16_supported() else "eager")
        model = PeftModel.from_pretrained(model, args.lora_checkpoint)
        model = model.merge_and_unload()
        model = model.to(device).eval()
    else:
        if accelerator.is_main_process:
            print("No LoRA checkpoint specified, loading base model.")
        model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True, attn_implementation="flash_attention_2" if torch.cuda.is_bf16_supported() else "eager").to(device).eval()
    
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = xxxx
    tokenizer.padding_side = "left"
    
    if accelerator.is_main_process:
        print("Model and tokenizer loaded successfully.")
    return model, tokenizer

def generate_prediction(model, tokenizer, prompt_text, device, temperature, max_tokens=4096):
    """Generates a prediction for a SINGLE prompt using the provided model."""
    messages = [{"role": "user", "content": prompt_text}]
    inputs = tokenizer.apply_chat_template(
        messages, return_tensors="pt", add_generation_prompt=True
    ).to(device)
    with torch.no_grad():
        outputs = model.generate(
            inputs, max_new_tokens=max_tokens, do_sample=True, temperature = temperature,
            pad_token_id=tokenizer.pad_token_id
        )
    response_ids = outputs[0, inputs.shape[1]:]
    response_text = tokenizer.decode(response_ids, skip_special_tokens=True)
    return response_text.strip()

def generate_batch_predictions(model, tokenizer, prompts, device, temperature, max_tokens=4096):
    """
    Generates predictions for a BATCH of prompts, significantly faster than one-by-one.
    """
    # This call returns a single tensor of padded input_ids
    input_ids = tokenizer.apply_chat_template(
        prompts,
        return_tensors="pt",
        add_generation_prompt=True,
        padding=True
    ).to(device)

    # We must create the attention_mask manually. It tells the model to ignore padding tokens.
    # It's a tensor of 1s for real tokens and 0s for padding tokens.
    attention_mask = (input_ids != tokenizer.pad_token_id).long().to(device)

    with torch.no_grad():
        # Pass input_ids and attention_mask as explicit keyword arguments
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_tokens,
            do_sample=True,
            temperature=temperature,
            pad_token_id=tokenizer.pad_token_id
        )

    # Slice the output to get only the generated text
    response_ids = outputs[:, input_ids.shape[1]:]
    response_texts = tokenizer.batch_decode(response_ids, skip_special_tokens=True)

    return [text.strip() for text in response_texts]


# (The format_revision_prompt and grade_revision functions are correct and unchanged)
def format_revision_prompt(cell_type, pert, initial_predictions):

    revision_header = (
        f"You are a senior biologist reviewing gene expression predictions from an experiment where the gene '{pert}' was knocked down in '{cell_type}' cells.\n\n"
        "The following initial predictions were generated by an automated preliminary analysis. This type of analysis is often overly sensitive and is known to produce a high number of **false positives**.\n\n"
        f"Your task is to apply stringent biological scrutiny. Re-classify any gene as **'not differentially expressed'** unless you are confident that the knockdown of '{pert}' led to a change in its expression. Be skeptical of the initial predictions.\n\n"
        "After your review, you MUST provide your final, corrected list in an XML format with <prediction> elements, each containing a <gene> and an <answer> ('upregulated', 'downregulated', or 'not differentially expressed').\n\n"
        "--- START OF INITIAL PREDICTIONS ---\n"
    )
    predictions_text_block = [f"- Gene: {item['gene']}\n- Prediction:\n{item['prediction']}" for item in initial_predictions]
    predictions_text_block_str = "\n\n".join(predictions_text_block)
    revision_footer = ("\n--- END OF INITIAL PREDICTIONS ---\n\n" "Now, provide your complete, revised list of predictions for ALL genes in the following XML format. " "Do not include any other text outside the main <revisions> block.\n" "Example format:\n" "<revisions>\n" "  <prediction>\n" "    <gene>GENE_A</gene>\n" "    <answer>downregulated</answer>\n" "  </prediction>\n" "  <prediction>\n" "    <gene>GENE_B</gene>\n" "    <answer>upregulated</answer>\n" "  </prediction>\n" "</revisions>")
    return revision_header + predictions_text_block_str + revision_footer

def grade_revision(initial_predictions, revision_xml_str):
    initial_answers = {}
    for pred in initial_predictions:
        gene = pred['gene']
        ground_truth = pred['ground_truth_label']
        match = re.search(r"<answer>(.*?)</answer>", pred['prediction'], re.IGNORECASE | re.DOTALL)
        initial_pred_answer = match.group(1).strip().lower() if match else "parsing_failed"
        initial_answers[gene] = {"prediction": initial_pred_answer, "ground_truth": ground_truth}
    revised_answers = {}
    try:
        xml_match = re.search(r"<revisions>.*?</revisions>", revision_xml_str, re.DOTALL)
        if xml_match:
            clean_xml_str = xml_match.group(0)
            root = ET.fromstring(clean_xml_str)
            for pred_node in root.findall('prediction'):
                gene_node, answer_node = pred_node.find('gene'), pred_node.find('answer')
                if gene_node is not None and answer_node is not None:
                    revised_answers[gene_node.text.strip()] = answer_node.text.strip().lower()
        else: raise ET.ParseError
    except ET.ParseError:
        return {"error": "Failed to parse revision XML.", "pre_revision_accuracy": -1, "post_revision_accuracy": -1}
    initial_correct, revised_correct, total_genes = 0, 0, len(initial_answers)
    if total_genes == 0: return {"pre_revision_accuracy": 100.0, "post_revision_accuracy": 100.0, "genes_evaluated": 0, "initial_correct": 0, "revised_correct": 0}
    for gene, data in initial_answers.items():
        if data["prediction"] == data["ground_truth"]: initial_correct += 1
        if gene in revised_answers and revised_answers[gene] == data["ground_truth"]: revised_correct += 1
    return {"pre_revision_accuracy": (initial_correct / total_genes) * 100, "post_revision_accuracy": (revised_correct / total_genes) * 100, "genes_evaluated": total_genes, "initial_correct": initial_correct, "revised_correct": revised_correct}


def main(args):
    accelerator = Accelerator()
    device = accelerator.device
    print(f"Process {accelerator.process_index} using device: {device}")

    predictor_model, predictor_tokenizer = load_model_and_tokenizer(args.predictor_model_path, args, device, accelerator)
    if args.reviser_model_path != args.predictor_model_path:
        del predictor_model
        torch.cuda.empty_cache()
        reviser_model, reviser_tokenizer = load_model_and_tokenizer(args.reviser_model_path, args, device, accelerator)
    else:
        reviser_model, reviser_tokenizer = predictor_model, predictor_tokenizer


    full_dataset = DiffExpressionDataset(csv_dir=args.data_dir, split='test', test_split_cell_lines=args.cell_line, generate_all_non_de_samples=args.generate_all_non_de_samples, generate_4x_non_de_samples=args.generate_4x_non_de_samples)
    total_samples = len(full_dataset)
    sample_size = int(total_samples * args.dataset_fraction)  # Use the dataset_fraction argument
    indices = random.sample(range(total_samples), sample_size)
    test_dataset = torch.utils.data.Subset(full_dataset, indices)
    df = pd.DataFrame([full_dataset[i] for i in indices])
    grouped_data = list(df.groupby(['cell_type', 'pert']))
    
    if args.limit_groups > 0:
        grouped_data = grouped_data[:args.limit_groups]

    output_path = Path(args.output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_output_file = output_path.with_name(f"temp_{accelerator.process_index}_{output_path.name}")
    
    results = []

    # --- MODIFIED WORK DISTRIBUTION AND PROGRESS BAR ---
    with accelerator.split_between_processes(grouped_data) as groups_iterator:
        groups_for_this_process = list(groups_iterator)
        
        #
        # --- FIX 1: HANDLE PROCESSES WITH NO WORK ---
        # If a process has no groups, it should skip the main loop entirely.
        #
        if not groups_for_this_process:
            print(f"Process {accelerator.process_index} has no groups to process. It will wait at the barrier.")
        else:
            total_genes_for_this_process = sum(len(group) for _, group in groups_for_this_process)

            if accelerator.is_main_process:
                 print(f"Main process (P0) will process {len(groups_for_this_process)} groups with a total of {total_genes_for_this_process} genes.")
            
            pbar = tqdm(total=total_genes_for_this_process, desc="Processing Genes", disable=not accelerator.is_main_process, unit="gene")

            for (cell_type, pert), group in groups_for_this_process:
                pbar.set_description(f"P{accelerator.process_index}: {cell_type}/{pert}")

                # --- 1. INITIAL PREDICTION (Your existing batching is good) ---
                predictor_prompts = []
                genes_in_group = []
                ground_truth_labels_in_group = []
                for row in group.to_dict('records'):
                    gene, label = row['gene'], row['label']
                    predictor_prompts.append(row['prompt'])
                    genes_in_group.append(gene)
                    ground_truth_labels_in_group.append(full_dataset.label_map[label])
                
                # Process initial predictions in chunks to manage memory
                chunk_size = args.chunk_size # Keep this at a reasonable size
                prediction_texts = []
                if predictor_prompts:
                    for i in range(0, len(predictor_prompts), chunk_size):
                        prompt_chunk = predictor_prompts[i:i+chunk_size]
                        prediction_texts.extend(
                            generate_batch_predictions(predictor_model, predictor_tokenizer, prompt_chunk, device, temperature = args.generation_temperature, max_tokens=args.max_tokens) # Reduced max_tokens for predictor
                        )
                
                initial_predictions = [{'gene': g, 'ground_truth_label': l, 'prediction': p} for g, l, p in zip(genes_in_group, ground_truth_labels_in_group, prediction_texts)]
                
                # --- 2. REVISION STEP WITH SUB-BATCHING (THE CRITICAL FIX) ---
                
                # Define a max size for each revision chunk to prevent OOM
                revision_chunk_size = args.revision_chunk_size  # Adjust based on your VRAM (50 is a safe start)
                final_revised_answers_map = {}
                all_revision_responses_text = []

                # Process the full list of predictions in smaller chunks
                for i in tqdm(range(0, len(initial_predictions), revision_chunk_size), desc=f"Revising {pert} in chunks", leave=False, disable=not accelerator.is_main_process):
                    prediction_chunk_for_revision = initial_predictions[i:i+revision_chunk_size]
                    
                    if not prediction_chunk_for_revision:
                        continue

                    # a. Format a smaller, manageable revision prompt
                    revision_prompt_chunk = format_revision_prompt(cell_type, pert, prediction_chunk_for_revision)

                    # b. Use a safe, capped max_tokens calculation
                    estimated_tokens = 40 * len(prediction_chunk_for_revision) + 200 # ~40 tokens per gene for XML
                    max_revision_tokens = min(estimated_tokens, 8192) # Cap at a safe limit

                    # c. Generate the revision for this chunk ONLY
                    revision_response_chunk = generate_prediction(reviser_model, reviser_tokenizer, revision_prompt_chunk, device, temperature = args.revision_temperature, max_tokens=max_revision_tokens)
                    all_revision_responses_text.append(revision_response_chunk)
                    if accelerator.is_main_process:
                        print(f"Revision prompt for {cell_type}/{pert} (chunk {i//revision_chunk_size + 1}):\n{revision_prompt_chunk}\n")
                        print(f"Revision response for {cell_type}/{pert} (chunk {i//revision_chunk_size + 1}):\n{revision_response_chunk}\n")
                    # d. Parse the XML from this chunk immediately and store the key-value pairs
                    try:
                        xml_match = re.search(r"<revisions>.*?</revisions>", revision_response_chunk, re.DOTALL)
                        if xml_match:
                            root = ET.fromstring(xml_match.group(0))
                            for pred_node in root.findall('prediction'):
                                gene_node, answer_node = pred_node.find('gene'), pred_node.find('answer')
                                if gene_node is not None and answer_node is not None and gene_node.text:
                                    final_revised_answers_map[gene_node.text.strip()] = answer_node.text.strip().lower()
                    except ET.ParseError:
                        accelerator.print(f"WARN: Failed to parse XML chunk for {cell_type}/{pert}. Skipping chunk.")

                # Explicitly clear memory after processing a large group
                torch.cuda.empty_cache()

                # --- 3. GRADING (Adapted for sub-batched results) ---
                # The original grade_revision function won't work. We grade against the map we built.
                initial_correct, revised_correct, total_genes = 0, 0, len(initial_predictions)
                
                if total_genes > 0:
                    for pred_item in initial_predictions:
                        gene = pred_item['gene']
                        ground_truth = pred_item['ground_truth_label']
                        
                        # Grade initial prediction
                        match = re.search(r"<answer>(.*?)</answer>", pred_item['prediction'], re.IGNORECASE | re.DOTALL)
                        initial_pred_answer = match.group(1).strip().lower() if match else "parsing_failed"
                        if initial_pred_answer == ground_truth:
                            initial_correct += 1

                        # Grade revised prediction by looking it up in our map
                        if gene in final_revised_answers_map and final_revised_answers_map[gene] == ground_truth:
                            revised_correct += 1
                    
                    grading_stats = {
                        "pre_revision_accuracy": (initial_correct / total_genes) * 100,
                        "post_revision_accuracy": (revised_correct / total_genes) * 100,
                        "genes_evaluated": total_genes, 
                        "initial_correct": initial_correct, 
                        "revised_correct": revised_correct
                    }
                else: # Handle empty groups
                    grading_stats = {"pre_revision_accuracy": 100.0, "post_revision_accuracy": 100.0, "genes_evaluated": 0, "initial_correct": 0, "revised_correct": 0}

                # For logging, combine all partial revision responses into one string
                full_revision_response_log = "\n\n--- REVISION CHUNK ---\n\n".join(all_revision_responses_text)

                # --- 4. SAVING RESULTS (NO CHANGE NEEDED HERE) ---
                results.append({
                    'cell_type': cell_type, 
                    'perturbation': pert, 
                    'grading_stats': grading_stats, 
                    'initial_predictions': initial_predictions, 
                    'revision_response': full_revision_response_log # Save the combined log
                })
                
                pbar.update(len(group))

    # --- FILE WRITING (NO CHANGE) ---
    if len(results) > 0:
        with open(temp_output_file, 'w', encoding='utf-8') as f_out:
            for res in results:
                f_out.write(json.dumps(res) + '\n')

    # All processes, including those with no work, will wait here.
    # Because the busy processes are now more balanced, they should all arrive here
    # around the same time, preventing the timeout.
    accelerator.wait_for_everyone()

    # --- GATHERING RESULTS (NO CHANGE) ---
    if accelerator.is_main_process:
        print("\nAll processes finished. Main process gathering results...")
        with open(output_path, 'w', encoding='utf-8') as f_final:
            for i in range(accelerator.num_processes):
                temp_file_to_read = output_path.with_name(f"temp_{i}_{output_path.name}")
                if temp_file_to_read.exists():
                    with open(temp_file_to_read, 'r', encoding='utf-8') as f_temp:
                        f_final.write(f_temp.read())
                    temp_file_to_read.unlink()
        print(f"Processing complete. Results saved to {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a two-stage prediction and revision pipeline for gene expression analysis.")
    parser.add_argument("--predictor_model_path", type=str, required=True, help="Path to the initial predictor model.")
    parser.add_argument("--reviser_model_path", type=str, required=True, help="Path to the reviser model.")
    parser.add_argument("--generate_all_non_de_samples", action="store_true", help="100x larger amount of not differentially expressed genes.")
    parser.add_argument("--generate_4x_non_de_samples", action="store_true", help="4x larger amount of not differentially expressed genes.")
    parser.add_argument("--data_dir", type=str, default="./data", help="Directory containing the dataset CSVs.")
    parser.add_argument("--output_file", type=str, default="./revision_experiment_results.jsonl", help="Path to the output JSONL file.")
    parser.add_argument("--limit_groups", type=int, default=0, help="Limit the number of (cell_type, perturbation) groups to process. 0 for all.")
    parser.add_argument("--lora_checkpoint", type=str, default=None, help="Path to LoRA checkpoint for the model(s).")
    parser.add_argument("--cell_line", type=str, default="none", help="List of cell lines to include in the test split.")
    parser.add_argument("--dataset_fraction", type=float, default=1.0, help="Fraction of the dataset to use for testing (0.0 to 1.0).")
    parser.add_argument("--chunk_size", type=int, default=32, help="Size of each chunk for batched generation.")
    parser.add_argument("--revision_chunk_size", type=int, default=50, help="Size of each chunk for revision generation.")
    parser.add_argument("--generation_temperature", type=float, default=1.0, help="Temperature for sampling in generation.")
    parser.add_argument("--revision_temperature", type=float, default=1.0, help="Temperature for sampling in revision generation.")
    parser.add_argument("--max_tokens", type=int, default=4096, help="Maximum number of tokens for generation.")


    args = parser.parse_args()
    main(args)