import argparse
import json
import pandas as pd
import torch
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
import re
import xml.etree.ElementTree as ET
from peft import PeftModel
from accelerate import Accelerator
import random
from collections import defaultdict, Counter

from src.data import DiffExpressionDataset

def load_model_and_tokenizer(model_path, args, device, accelerator):
    """Loads a Hugging Face model and tokenizer to a specific device."""
    if accelerator.is_main_process:
        print(f"Loading model from: {model_path}")
        
    if args.lora_checkpoint:
        model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16, trust_remote_code=True, attn_implementation="flash_attention_2" if torch.cuda.is_bf16_supported() else "eager")
        model = PeftModel.from_pretrained(model, args.lora_checkpoint)
        model = model.merge_and_unload()
        model = model.to(device).eval()
    else:
        if accelerator.is_main_process:
            print("No LoRA checkpoint specified, loading base model.")
        model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, trust_remote_code=True, attn_implementation="flash_attention_2" if torch.cuda.is_bf16_supported() else "eager").to(device).eval()
    
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = xxxx
    tokenizer.padding_side = "left"
    
    if accelerator.is_main_process:
        print("Model and tokenizer loaded successfully.")
    return model, tokenizer

def generate_prediction(model, tokenizer, prompt_text, device, temperature, max_tokens=4096):
    """Generates a prediction for a SINGLE prompt using the provided model."""
    messages = [{"role": "user", "content": prompt_text}]
    inputs = tokenizer.apply_chat_template(
        messages, return_tensors="pt", add_generation_prompt=True
    ).to(device)
    with torch.no_grad():
        outputs = model.generate(
            inputs, max_new_tokens=max_tokens, do_sample=True, temperature=temperature,
            pad_token_id=tokenizer.pad_token_id
        )
    response_ids = outputs[0, inputs.shape[1]:]
    response_text = tokenizer.decode(response_ids, skip_special_tokens=True)
    return response_text.strip()

def generate_batch_predictions(model, tokenizer, prompts, device, temperature, max_tokens=4096):
    """Generates predictions for a BATCH of prompts."""
    input_ids = tokenizer.apply_chat_template(
        prompts, return_tensors="pt", add_generation_prompt=True, padding=True
    ).to(device)
    attention_mask = (input_ids != tokenizer.pad_token_id).long().to(device)
    with torch.no_grad():
        outputs = model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=max_tokens,
            do_sample=True,
            temperature=temperature,
            pad_token_id=tokenizer.pad_token_id
        )
    response_ids = outputs[:, input_ids.shape[1]:]
    response_texts = tokenizer.batch_decode(response_ids, skip_special_tokens=True)
    return [text.strip() for text in response_texts]

def format_revision_prompt_with_reasoning(cell_type, pert, predictions_by_gene):
    """
    Formats a revision prompt asking the model to choose the best prediction from a list
    and provide reasoning.
    """
    revision_header = (
        f"You are a senior biologist tasked with consolidating multiple gene expression predictions. "
        f"The experiment involves knocking down the gene '{pert}' in '{cell_type}' cells.\n\n"
        "For each target gene below, you are given several independent predictions. Your task is to:\n"
        "1. Analyze all predictions for the gene.\n"
        "2. Write a brief reasoning for your final decision based on biological plausibility.\n"
        "3. Provide a single, final 'best' answer.\n\n"
        "The following initial predictions were generated by an automated preliminary analysis. This type of analysis is often overly sensitive and is known to produce a high number of **false positives**.\n\n"
        f"Your task is to apply stringent biological scrutiny. Re-classify any gene as **'not differentially expressed'** unless you are confident that the knockdown of '{pert}' led to a change in its expression. Be skeptical of the initial predictions.\n\n"
        "You MUST provide your final, corrected list in an XML format. The XML must contain a list of "
        "<prediction> elements, each with a <gene>, <reasoning>, and <answer> tag. The 'answer' must be one "
        "of 'upregulated', 'downregulated', or 'not differentially expressed'.\n\n"
        "--- START OF INITIAL PREDICTIONS ---\n"
    )

    predictions_text_block = []
    for gene, preds in predictions_by_gene.items():
        gene_header = f"- Gene: {gene}\n- Predictions to review:\n"
        pred_list = [f"  - Prediction {i+1}: {p}" for i, p in enumerate(preds)]
        predictions_text_block.append(gene_header + "\n".join(pred_list))
    
    predictions_text_block_str = "\n\n".join(predictions_text_block)

    revision_footer = (
        "\n--- END OF INITIAL PREDICTIONS ---\n\n"
        "Now, provide your complete, consolidated list of predictions for ALL genes in the following XML format. "
        "Do not include any other text outside the main <revisions> block.\n"
        "Example format:\n"
        "<revisions>\n"
        "  <prediction>\n"
        "    <gene>GENE_A</gene>\n"
        "    <reasoning>The first two predictions contradict each other, but the third aligns with the known pathway where knocking down {pert} often leads to compensatory upregulation of GENE_A.</reasoning>\n"
        "    <answer>upregulated</answer>\n"
        "  </prediction>\n"
        "  <prediction>\n"
        "    <gene>GENE_B</gene>\n"
        "    <reasoning>All three initial predictions consistently point to downregulation, which is expected.</reasoning>\n"
        "    <answer>downregulated</answer>\n"
        "  </prediction>\n"
        "</revisions>"
    )
    return revision_header + predictions_text_block_str + revision_footer

def parse_answer_from_prediction(prediction_text):
    """Extracts the answer from a prediction's XML-like response."""
    match = re.search(r"<answer>(.*?)</answer>", prediction_text, re.IGNORECASE | re.DOTALL)
    return match.group(1).strip().lower() if match else "parsing_failed"


def main(args):
    accelerator = Accelerator()
    device = accelerator.device
    print(f"Process {accelerator.process_index} using device: {device}")

    # --- MODEL LOADING ---
    predictor_model, predictor_tokenizer = load_model_and_tokenizer(args.predictor_model_path, args, device, accelerator)
    if args.reviser_model_path != args.predictor_model_path:
        del predictor_model
        torch.cuda.empty_cache()
        reviser_model, reviser_tokenizer = load_model_and_tokenizer(args.reviser_model_path, args, device, accelerator)
    else:
        reviser_model, reviser_tokenizer = predictor_model, predictor_tokenizer

    # --- DATA LOADING   --- 
    full_dataset = DiffExpressionDataset(csv_dir=args.data_dir, split='test', test_split_cell_lines=args.cell_line, generate_all_non_de_samples=args.generate_all_non_de_samples, generate_4x_non_de_samples=args.generate_4x_non_de_samples)
    total_samples = len(full_dataset)
    sample_size = int(total_samples * args.dataset_fraction)  # Use the dataset_fraction argument
    indices = random.sample(range(total_samples), sample_size)
    test_dataset = torch.utils.data.Subset(full_dataset, indices)
    df = pd.DataFrame([full_dataset[i] for i in indices])
    grouped_data = list(df.groupby(['cell_type', 'pert']))
    
    if args.limit_groups > 0:
        grouped_data = grouped_data[:args.limit_groups]

    output_path = Path(args.output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temp_output_file = output_path.with_name(f"temp_{accelerator.process_index}_{output_path.name}")
    
    results = []

    # --- WORK DISTRIBUTION ---
    with accelerator.split_between_processes(grouped_data) as groups_iterator:
        groups_for_this_process = list(groups_iterator)
        
        if not groups_for_this_process:
            print(f"Process {accelerator.process_index} has no groups to process.")
        else:
            total_genes_to_process = sum(len(group) for _, group in groups_for_this_process)
            pbar = tqdm(total=total_genes_to_process, desc="Processing Genes", disable=not accelerator.is_main_process, unit="gene")

            for (cell_type, pert), group in groups_for_this_process:
                pbar.set_description(f"P{accelerator.process_index}: {cell_type}/{pert}")

                # ===================================================================================
                # STEP 1 & 2: PARALLEL STREAMS & ASSEMBLY (Performed efficiently)
                # ===================================================================================
                # We build a single large batch that contains the prompts for all genes,
                # with each gene's prompt repeated n_gen times. This is equivalent to your
                # "parallel streams" concept but optimized for the GPU.
                predictor_prompts = []
                gene_for_each_prompt = []
                ground_truth_map = {}
                
                for row in group.to_dict('records'):
                    # For each gene, add its prompt n_gen times to the batch
                    for _ in range(args.n_gen):
                        predictor_prompts.append(row['prompt'])
                        gene_for_each_prompt.append(row['gene'])
                    ground_truth_map[row['gene']] = full_dataset.label_map[row['label']]
                
                # Generate all predictions. Because do_sample=True, the repeated prompts
                # will yield different, independent predictions. This single call performs
                # all 'n_gen' streams at once.
                prediction_texts = []
                if predictor_prompts:
                    for i in range(0, len(predictor_prompts), args.chunk_size):
                        prompt_chunk = predictor_prompts[i:i+args.chunk_size]
                        prediction_texts.extend(
                            generate_batch_predictions(
                                predictor_model, predictor_tokenizer, prompt_chunk, device, 
                                temperature=args.generation_temperature, max_tokens=256
                            )
                        )
                
                # Here, we perform the "Assembly" step. We group the flat list of predictions
                # by their corresponding gene.
                initial_predictions_by_gene = defaultdict(list)
                for gene, pred_text in zip(gene_for_each_prompt, prediction_texts):
                    initial_predictions_by_gene[gene].append(pred_text)
                
                # ===================================================================================
                # STEP 3: REVISE WITH FULL CONTEXT
                # ===================================================================================
                # This function now receives the fully assembled list of n_gen predictions for every gene.
                revision_prompt = format_revision_prompt_with_reasoning(cell_type, pert, initial_predictions_by_gene)
                
                estimated_tokens = 60 * len(initial_predictions_by_gene) + 500
                max_revision_tokens = min(estimated_tokens, args.max_tokens)
                
                revision_response = generate_prediction(reviser_model, reviser_tokenizer, revision_prompt, device, temperature=args.revision_temperature, max_tokens=max_revision_tokens)

                # --- GRADING & SAVING (Logic remains the same) ---
                initial_correct = 0
                for gene, preds in initial_predictions_by_gene.items():
                    parsed_answers = [parse_answer_from_prediction(p) for p in preds]
                    counts = Counter(ans for ans in parsed_answers if ans != "parsing_failed")
                    if not counts:
                        majority_vote = "parsing_failed"
                    else:
                        majority_vote = counts.most_common(1)[0][0]
                    if majority_vote == ground_truth_map[gene]:
                        initial_correct += 1

                revised_correct = 0
                try:
                    xml_match = re.search(r"<revisions>.*?</revisions>", revision_response, re.DOTALL)
                    if xml_match:
                        root = ET.fromstring(xml_match.group(0))
                        for pred_node in root.findall('prediction'):
                            gene_node, answer_node = pred_node.find('gene'), pred_node.find('answer')
                            if gene_node is not None and answer_node is not None and gene_node.text:
                                gene = gene_node.text.strip()
                                answer = answer_node.text.strip().lower()
                                if gene in ground_truth_map and answer == ground_truth_map[gene]:
                                    revised_correct += 1
                except ET.ParseError:
                    accelerator.print(f"WARN: Failed to parse revision XML for {cell_type}/{pert}.")

                total_genes = len(ground_truth_map)
                grading_stats = {
                    "pre_revision_accuracy": (initial_correct / total_genes) * 100 if total_genes > 0 else 100.0,
                    "post_revision_accuracy": (revised_correct / total_genes) * 100 if total_genes > 0 else 100.0,
                    "genes_evaluated": total_genes,
                    "initial_correct_majority_vote": initial_correct,
                    "revised_correct": revised_correct
                }
                
                results.append({
                    'cell_type': cell_type, 
                    'perturbation': pert, 
                    'grading_stats': grading_stats, 
                    'initial_predictions_by_gene': dict(initial_predictions_by_gene),
                    'revision_prompt': revision_prompt,
                    'revision_response': revision_response
                })
                
                pbar.update(len(group))
                torch.cuda.empty_cache()

    # --- FILE WRITING AND GATHERING (Unchanged) ---
    if len(results) > 0:
        with open(temp_output_file, 'w', encoding='utf-8') as f_out:
            for res in results:
                f_out.write(json.dumps(res) + '\n')

    accelerator.wait_for_everyone()

    if accelerator.is_main_process:
        print("\nAll processes finished. Main process gathering results...")
        with open(output_path, 'w', encoding='utf-8') as f_final:
            for i in range(accelerator.num_processes):
                temp_file_to_read = output_path.with_name(f"temp_{i}_{output_path.name}")
                if temp_file_to_read.exists():
                    with open(temp_file_to_read, 'r', encoding='utf-8') as f_temp:
                        f_final.write(f_temp.read())
                    temp_file_to_read.unlink()
        print(f"Processing complete. Results saved to {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a multi-generation prediction and reasoned revision pipeline.")
    parser.add_argument("--n_gen", type=int, default=3, help="Number of initial predictions to generate per gene.")
    parser.add_argument("--predictor_model_path", type=str, required=True, help="Path to the initial predictor model.")
    parser.add_argument("--reviser_model_path", type=str, required=True, help="Path to the reviser model.")
    parser.add_argument("--data_dir", type=str, default="./data", help="Directory containing the dataset CSVs.")
    parser.add_argument("--output_file", type=str, default="./revision_experiment_results_multisample.jsonl", help="Path to the output JSONL file.")
    parser.add_argument("--limit_groups", type=int, default=0, help="Limit the number of (cell_type, perturbation) groups. 0 for all.")
    parser.add_argument("--lora_checkpoint", type=str, default=None, help="Path to LoRA checkpoint for the model(s).")
    parser.add_argument("--cell_line", type=str, default="none")
    parser.add_argument("--dataset_fraction", type=float, default=1.0)
    parser.add_argument("--chunk_size", type=int, default=32, help="Size of each chunk for batched generation.")
    parser.add_argument("--generation_temperature", type=float, default=0.8, help="Temperature for initial prediction sampling.")
    parser.add_argument("--revision_temperature", type=float, default=0.4, help="Temperature for revision generation sampling.")
    parser.add_argument("--max_tokens", type=int, default=8192, help="Maximum number of new tokens for generation.")
    parser.add_argument("--generate_all_non_de_samples", action="store_true")
    parser.add_argument("--generate_4x_non_de_samples", action="store_true")

    args = parser.parse_args()
    main(args)